data_path: ../data/skills/train_images/
#data_path: ../data/skills/Armor_01/
#img_shape: [256, 256]
img_shape: [64, 64]
img_channels: 3
transform: diffusion_transform
shuffle: True
batch_size: 64
eval_batches: 2
num_workers: 16
device: cuda
extend_dataset_times: 8

trainer: GeneratorTrainer
generated_images_savepath: exps/images